// <auto-generated />
using System;
using Auth.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Auth.Data.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("MySql:CharSet", "utf8mb4");

            modelBuilder.Entity("Auth.Business.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("char(36)")
                    .HasColumnName("id")
                    .HasAnnotation("MySql:CharSet", "utf8mb4");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp(6)")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                b.Property<bool>("IsActive")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasColumnName("is_active")
                    .HasDefaultValue(true);

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)")
                    .HasColumnName("password_hash")
                    .HasAnnotation("MySql:CharSet", "utf8mb4");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)")
                    .HasColumnName("username")
                    .HasAnnotation("MySql:CharSet", "utf8mb4");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("timestamp(6)")
                    .HasColumnName("updated_at")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                b.HasKey("Id");

                b.HasIndex("Username")
                    .IsUnique();

                b.ToTable("users").HasAnnotation("MySql:CharSet", "utf8mb4");
            });
#pragma warning restore 612, 618
        }
    }
}
